name 'gh2558_test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures gh2558_test'
long_description 'Installs/Configures gh2558_test'
version '0.1.0'
